name: CI Section 24
on:
  pull_request:
    branches:
      - "master"
jobs:
  testing:
    runs-on: ubuntu-latest
    name: unitest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: run unit test
        uses: go test -v ./...
      - name: run linting
        uses: golangci/golangci-lint-action@v3